language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

dist: trusty

sudo: false

before_install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script: vendor/bin/phpunit --verbose
